/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package smb.schema;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class Sales extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -2620094293409498893L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Sales\",\"namespace\":\"smb.schema\",\"fields\":[{\"name\":\"userId\",\"type\":\"int\"},{\"name\":\"orderValue\",\"type\":\"int\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<Sales> ENCODER =
      new BinaryMessageEncoder<Sales>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<Sales> DECODER =
      new BinaryMessageDecoder<Sales>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<Sales> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<Sales> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<Sales>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this Sales to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a Sales from a ByteBuffer. */
  public static Sales fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public int userId;
  @Deprecated public int orderValue;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public Sales() {}

  /**
   * All-args constructor.
   * @param userId The new value for userId
   * @param orderValue The new value for orderValue
   */
  public Sales(java.lang.Integer userId, java.lang.Integer orderValue) {
    this.userId = userId;
    this.orderValue = orderValue;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return userId;
    case 1: return orderValue;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: userId = (java.lang.Integer)value$; break;
    case 1: orderValue = (java.lang.Integer)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'userId' field.
   * @return The value of the 'userId' field.
   */
  public java.lang.Integer getUserId() {
    return userId;
  }

  /**
   * Sets the value of the 'userId' field.
   * @param value the value to set.
   */
  public void setUserId(java.lang.Integer value) {
    this.userId = value;
  }

  /**
   * Gets the value of the 'orderValue' field.
   * @return The value of the 'orderValue' field.
   */
  public java.lang.Integer getOrderValue() {
    return orderValue;
  }

  /**
   * Sets the value of the 'orderValue' field.
   * @param value the value to set.
   */
  public void setOrderValue(java.lang.Integer value) {
    this.orderValue = value;
  }

  /**
   * Creates a new Sales RecordBuilder.
   * @return A new Sales RecordBuilder
   */
  public static smb.schema.Sales.Builder newBuilder() {
    return new smb.schema.Sales.Builder();
  }

  /**
   * Creates a new Sales RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new Sales RecordBuilder
   */
  public static smb.schema.Sales.Builder newBuilder(smb.schema.Sales.Builder other) {
    return new smb.schema.Sales.Builder(other);
  }

  /**
   * Creates a new Sales RecordBuilder by copying an existing Sales instance.
   * @param other The existing instance to copy.
   * @return A new Sales RecordBuilder
   */
  public static smb.schema.Sales.Builder newBuilder(smb.schema.Sales other) {
    return new smb.schema.Sales.Builder(other);
  }

  /**
   * RecordBuilder for Sales instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Sales>
    implements org.apache.avro.data.RecordBuilder<Sales> {

    private int userId;
    private int orderValue;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(smb.schema.Sales.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.userId)) {
        this.userId = data().deepCopy(fields()[0].schema(), other.userId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.orderValue)) {
        this.orderValue = data().deepCopy(fields()[1].schema(), other.orderValue);
        fieldSetFlags()[1] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing Sales instance
     * @param other The existing instance to copy.
     */
    private Builder(smb.schema.Sales other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.userId)) {
        this.userId = data().deepCopy(fields()[0].schema(), other.userId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.orderValue)) {
        this.orderValue = data().deepCopy(fields()[1].schema(), other.orderValue);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'userId' field.
      * @return The value.
      */
    public java.lang.Integer getUserId() {
      return userId;
    }

    /**
      * Sets the value of the 'userId' field.
      * @param value The value of 'userId'.
      * @return This builder.
      */
    public smb.schema.Sales.Builder setUserId(int value) {
      validate(fields()[0], value);
      this.userId = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'userId' field has been set.
      * @return True if the 'userId' field has been set, false otherwise.
      */
    public boolean hasUserId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'userId' field.
      * @return This builder.
      */
    public smb.schema.Sales.Builder clearUserId() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'orderValue' field.
      * @return The value.
      */
    public java.lang.Integer getOrderValue() {
      return orderValue;
    }

    /**
      * Sets the value of the 'orderValue' field.
      * @param value The value of 'orderValue'.
      * @return This builder.
      */
    public smb.schema.Sales.Builder setOrderValue(int value) {
      validate(fields()[1], value);
      this.orderValue = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'orderValue' field has been set.
      * @return True if the 'orderValue' field has been set, false otherwise.
      */
    public boolean hasOrderValue() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'orderValue' field.
      * @return This builder.
      */
    public smb.schema.Sales.Builder clearOrderValue() {
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public Sales build() {
      try {
        Sales record = new Sales();
        record.userId = fieldSetFlags()[0] ? this.userId : (java.lang.Integer) defaultValue(fields()[0]);
        record.orderValue = fieldSetFlags()[1] ? this.orderValue : (java.lang.Integer) defaultValue(fields()[1]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<Sales>
    WRITER$ = (org.apache.avro.io.DatumWriter<Sales>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<Sales>
    READER$ = (org.apache.avro.io.DatumReader<Sales>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
